// Generated by Selenium ID



import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.jupiter.api.AfterEach;

import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import io.qameta.allure.Attachment;


public class TriangleTest {
	
  private WebDriver driver;
  
  @Before
  public void setUp() {
    
    System.setProperty("webdriver.chrome.driver", "C:\\driver\\chromedriver.exe");
    driver = (WebDriver) new ChromeDriver();
    }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @AfterEach
  public void takeScreenTest() {
      makeScreenshot();
  }

@Attachment(value = "Attachment Screenshot", type = "image/png")
  public byte[] makeScreenshot() {
      return ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
  }
  
  
  @Test
  public void acuteScaleneTriangle() {
    driver.get("https://www.calculator.net/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(888, 835));
    driver.findElement(By.cssSelector(".clearbtn")).click();
    driver.findElement(By.name("vx")).click();
    driver.findElement(By.name("vx")).sendKeys("6");
    driver.findElement(By.name("vy")).click();
    driver.findElement(By.name("vy")).sendKeys("7");
    driver.findElement(By.name("vz")).click();
    driver.findElement(By.name("vz")).sendKeys("4");
    driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
    assertEquals(driver.findElement(By.cssSelector("td > h3")).getText(), "Acute Scalene Triangle");
    driver.close();
  }
  
  @Test
  public void empty1side() {
    driver.get("https://www.calculator.net/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(888, 835));
    driver.findElement(By.cssSelector(".clearbtn")).click();
    driver.findElement(By.name("vx")).click();
    driver.findElement(By.name("vx")).sendKeys("5");
    driver.findElement(By.name("vy")).click();
    driver.findElement(By.name("vy")).sendKeys("5");
    driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
    assertEquals(driver.findElement(By.cssSelector("font")).getText(), "Please provide 3 positive values, including at least one side.");
    driver.close();
  }
  
  @Test
  public void equilateralTriangle() {
    driver.get("https://www.calculator.net/triangle-calculator.html/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(888, 835));
    driver.findElement(By.cssSelector(".clearbtn")).click();
    driver.findElement(By.name("vx")).click();
    driver.findElement(By.name("vx")).sendKeys("5");
    driver.findElement(By.name("vy")).click();
    driver.findElement(By.name("vy")).sendKeys("5");
    driver.findElement(By.name("vz")).click();
    driver.findElement(By.name("vz")).sendKeys("5");
    driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
    assertEquals(driver.findElement(By.cssSelector("td > h3")).getText(), "Equilateral Triangle");
    driver.close();
  }
  @Test
  public void nottriangle() {
    driver.get("https://www.calculator.net/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(888, 835));
    driver.findElement(By.cssSelector(".clearbtn")).click();
    driver.findElement(By.name("vx")).click();
    driver.findElement(By.name("vx")).sendKeys("1");
    driver.findElement(By.name("vy")).click();
    driver.findElement(By.name("vy")).sendKeys("10");
    driver.findElement(By.name("vz")).click();
    driver.findElement(By.name("vz")).sendKeys("2");
    driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
    assertEquals(driver.findElement(By.cssSelector("td > h3")).getText(), "The sum of two sides must be larger than the third.");
    driver.close();
  }
  @Test
  public void obtuseScaleneTriangle() {
    driver.get("https://www.calculator.net/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(888, 835));
    driver.findElement(By.cssSelector(".clearbtn")).click();
    driver.findElement(By.name("vx")).click();
    driver.findElement(By.name("vx")).sendKeys("2");
    driver.findElement(By.name("vy")).click();
    driver.findElement(By.name("vy")).sendKeys("3");
    driver.findElement(By.name("vz")).click();
    driver.findElement(By.name("vz")).sendKeys("4");
    driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
    assertEquals(driver.findElement(By.cssSelector("td > h3")).getText(), "Obtuse Scalene Triangle");
  }
}
